### ISSUE TITLE
API returning 200 but wrapper returns an error

### ISSUE THREAD

**Issue by ghigo** [eaze/eaze-request#4]
Here is the api request
```
Request URL:https://api-development.eazeup.com/api/users/current/mobilePhone
Request Method:POST
Status Code:200 OK
Remote Address:52.207.119.46:443
Response Headers
view source
Access-Control-Allow-Origin:*
Connection:keep-alive
Content-Length:0
Date:Fri, 30 Sep 2016 00:44:24 GMT
Request-Id:citp1rm6rdldp2zm6j950uqcd
Server:nginx/1.10.1
Request Headers
view source
Accept:application/json
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:28
Content-Type:application/json
Host:api-development.eazeup.com
Origin:http://localhost:9966
Referer:http://localhost:9966/verify/phone
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
X-Auth-Token:D8B481CF3A0F513E8C236CCB298D25A31566E0B0C5F8B2CB34EEC1531E50B67752449E9B6EBBD5589583BE166B8FEA360F0CB6A137DCE5A6134A24101C13880354EDB1CB6EB9CDB11AFE43E71DBD9F0B79677FC6
Request Payload
view source
{mobilePhone: "5557898767"}
mobilePhone
:
"5557898767"
```
 and this is the object returned:
```
Error: We're having trouble reaching Eaze's servers—please try again.
    at clientError (http://localhost:9966/bundle.js:43716:18)
    at handleResponse (http://localhost:9966/bundle.js:43703:31)
    at Object.xhrRequestResult [as callback] (http://localhost:9966/bundle.js:43983:15)
    at cbOnce (http://localhost:9966/bundle.js:44054:22)
    at loadFunc (http://localhost:9966/bundle.js:44130:17)
    at XMLHttpRequest.readystatechange (http://localhost:9966/bundle.js:44060:14)
```

@hanford FYI

**Comment by bendrucker** [comment]
You have to include the `{responseType: ''}` in the options for routes that do not send a response. Otherwise it ends up triggering an error when trying to parse the result as JSON:

https://github.com/Jam3/xhr-request/blob/b0b9b2afdf576e9d4c02369c4896df0c5395f674/lib/request-browser.js#L17-L22

**Comment by ghigo** [comment]
Thanks
